### ISSUE TITLE
User ID QRCode

### ISSUE THREAD

**Issue by RoxyBoxxy** [RoxyBoxxy/VRChat-Mobile-Unoffical-#7]
Adding a qr code for users to add other uses via taking a picture

Works 50%
Issue: needs to click in the text area for the qr code to be gend

**Comment by sulha199** [comment]
Hi,

Have you tried the barcode scanner sdk such as https://github.com/zxing/zxing?

**Comment by RoxyBoxxy** [comment]
> Hi,
> 
> Have you tried the barcode scanner sdk such as https://github.com/zxing/zxing?

I am using this addon phonegap-plugin-barcodescanner

**Comment by sulha199** [comment]
Do you mean that clicking the text area of qr code is required to make the camera focus on the qr code? Are you still only testing it using laptop webcamera?

**Comment by RoxyBoxxy** [comment]
No it gets a string of text from a json and generates a qr code out of the text
