### ISSUE TITLE
[Bug] Does not allow login with 2-Step Enabled Accounts

### ISSUE THREAD

**Issue by UiharuKazari2008** [RoxyBoxxy/VRChat-Mobile-Unoffical-#8]
When I attempted to login it gave me a 401 error and then acted as if it was loading but then gave loops of the same 401 error

did not prompt for the login code

Phone: Xperia XZ Premium (EU Firmware) with Android O

**Comment by RoxyBoxxy** [comment]
Dev of this app has stopped how ever i think the VRChat website works well on mobile now
